In [2]:
import numpy as np
import pandas as pd

# Education

In [3]:
# add module e unpaid appreticeship

edu_data = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_c.csv')
edu_data = edu_data[['case_id', 'hh_c22a', 'hh_c22b', 'hh_c22c', 'hh_c22d', 'hh_c22e', 'hh_c22f', 'hh_c22g', 'hh_c22h', 'hh_c22i', 'hh_c22j']]
edu_data = edu_data.replace(np.nan, 0)
edu_data = edu_data.groupby(['case_id']).sum()
edu_data

/home/insauer/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (12,14) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,hh_c22a,hh_c22b,hh_c22c,hh_c22d,hh_c22e,hh_c22f,hh_c22g,hh_c22h,hh_c22i,hh_c22j
case_id,,,,,,,,,,
101010160009,0.0,0.0,0.0,0.0,2000.0,0.0,0.0,0.0,0.0,2000.0
101010160033,0.0,0.0,0.0,0.0,0.0,300.0,0.0,0.0,800.0,1100.0
101010160060,0.0,0.0,1400.0,1500.0,0.0,500.0,0.0,0.0,0.0,3400.0
101010160068,0.0,0.0,900.0,500.0,0.0,250.0,0.0,0.0,0.0,1650.0
101010160069,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
315556140342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140411,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140434,0.0,200.0,400.0,3100.0,0.0,400.0,0.0,0.0,0.0,4100.0

In [4]:
edu_data_e = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_e.csv')
edu_data_e = edu_data_e[['case_id', 'hh_e54']]
edu_data_e = edu_data_e.replace(np.nan, 0)
edu_data_e = edu_data_e.groupby(['case_id']).sum()
edu_data_e

/home/insauer/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (65) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

              hh_e54
case_id
101010160009     0.0
101010160033     0.0
101010160060     0.0
101010160068     0.0
101010160069     0.0
...              ...
315556140342     0.0
315556140365     0.0
315556140388     0.0
315556140411     0.0
315556140434     0.0

[12271 rows x 1 columns]

In [5]:
edu_data['unpaid_apprtzshp']=edu_data_e['hh_e54']
edu_data

,hh_c22a,hh_c22b,hh_c22c,hh_c22d,hh_c22e,hh_c22f,hh_c22g,hh_c22h,hh_c22i,hh_c22j,unpaid_apprtzshp
case_id,,,,,,,,,,,
101010160009,0.0,0.0,0.0,0.0,2000.0,0.0,0.0,0.0,0.0,2000.0,0.0
101010160033,0.0,0.0,0.0,0.0,0.0,300.0,0.0,0.0,800.0,1100.0,0.0
101010160060,0.0,0.0,1400.0,1500.0,0.0,500.0,0.0,0.0,0.0,3400.0,0.0
101010160068,0.0,0.0,900.0,500.0,0.0,250.0,0.0,0.0,0.0,1650.0,0.0
101010160069,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
315556140342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140411,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140434,0.0,200.0,400.0,3100.0,0.0,400.0,0.0,0.0,0.0,4100.0,0.0

In [6]:
consum=pd.DataFrame()
consum['education']=edu_data['hh_c22j']+edu_data['unpaid_apprtzshp']
consum

              education
case_id
101010160009     2000.0
101010160033     1100.0
101010160060     3400.0
101010160068     1650.0
101010160069        0.0
...                 ...
315556140342        0.0
315556140365        0.0
315556140388        0.0
315556140411        0.0
315556140434     4100.0

[12271 rows x 1 columns]

# Health

In [7]:
hlth_data = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_d.csv')
hlth_data = hlth_data[['case_id', 'hh_d10', 'hh_d11', 'hh_d12', 'hh_d14', 'hh_d15', 'hh_d16', 'hh_d19', 'hh_d20','hh_d21']]
hlth_data = hlth_data.replace(np.nan, 0)
hlth_data = hlth_data.groupby(['case_id']).sum()
hlth_data

/home/insauer/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (13,19,47,67) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,hh_d10,hh_d11,hh_d12,hh_d14,hh_d15,hh_d16,hh_d19,hh_d20,hh_d21
case_id,,,,,,,,,
101010160009,0.0,0.0,250.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160033,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160068,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160069,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
315556140342,0.0,0.0,160.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140365,0.0,0.0,0.0,2000.0,600.0,0.0,0.0,0.0,0.0
315556140388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140411,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
hlth_data['monthly_exp']=hlth_data['hh_d10']+hlth_data['hh_d11']+hlth_data['hh_d12']
hlth_data['annual_exp']=hlth_data.iloc[:,3:8].sum(axis=1)
hlth_data['total']=hlth_data['monthly_exp']*12+hlth_data['annual_exp']
hlth_data

,hh_d10,hh_d11,hh_d12,hh_d14,hh_d15,hh_d16,hh_d19,hh_d20,hh_d21,monthly_exp,annual_exp,total
case_id,,,,,,,,,,,,
101010160009,0.0,0.0,250.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,0.0,3000.0
101010160033,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,200.0,0.0,2400.0
101010160060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160068,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,1200.0
101010160069,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,1200.0
...,...,...,...,...,...,...,...,...,...,...,...,...
315556140342,0.0,0.0,160.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,0.0,1920.0
315556140365,0.0,0.0,0.0,2000.0,600.0,0.0,0.0,0.0,0.0,0.0,2600.0,2600.0
315556140388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140411,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0,200.0,0.0,2400.0
315556140434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
consum['health']=hlth_data['total']
consum

              education  health
case_id
101010160009     2000.0  3000.0
101010160033     1100.0  2400.0
101010160060     3400.0     0.0
101010160068     1650.0  1200.0
101010160069        0.0  1200.0
...                 ...     ...
315556140342        0.0  1920.0
315556140365        0.0  2600.0
315556140388        0.0     0.0
315556140411        0.0  2400.0
315556140434     4100.0     0.0

[12271 rows x 2 columns]

# Housing

In [83]:
house_data = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_f.csv')
house_data = house_data[['case_id', 'hh_f04a', 'hh_f04b','hh_f18', 'hh_f25', 'hh_f26a', 'hh_f26b', 'hh_f35', 'hh_f37']]
house_data = house_data.replace(np.nan, 0)
house_data = house_data.groupby(['case_id']).sum()
house_data = house_data.rename(columns={'hh_f04a': 'rent', 'hh_f18': 'firewood', 'hh_f25': 'electricity',
                                        'hh_f35': 'cell_phones', 'hh_f37': 'drinking_water'})
house_data

/home/insauer/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (14,16) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,rent,hh_f04b,firewood,electricity,hh_f26a,hh_f26b,cell_phones,drinking_water
case_id,,,,,,,,
101010160009,0.0,0.0,300.0,0.0,0.0,0.0,0.0,50.0
101010160033,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0
101010160060,0.0,0.0,500.0,0.0,0.0,0.0,300.0,100.0
101010160068,0.0,0.0,300.0,0.0,0.0,0.0,0.0,100.0
101010160069,0.0,0.0,50.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
315556140342,1000.0,5.0,470.0,0.0,0.0,0.0,800.0,50.0
315556140365,0.0,0.0,180.0,0.0,0.0,0.0,0.0,50.0
315556140388,1000.0,5.0,150.0,0.0,0.0,0.0,540.0,100.0
315556140411,700.0,5.0,400.0,0.0,0.0,0.0,1300.0,50.0
315556140434,0.0,0.0,400.0,0.0,0.0,0.0,12000.0,0.0

In [84]:
unit_dict = {3:365,
             4: 52,
             5: 12,
             6: 1,
             0: 0,
             1: 1}
def convert_unit(x):
    new_prize = x['rent']*unit_dict[x['hh_f04b']]
    
    return pd.Series(new_prize,
                     index=['housing'])

In [85]:
unit_dict = {3:365,
             4: 52,
             5: 12,
             6: 1,
             0: 0,
             1: 1,
             np.nan: 0.0}
def convert_unit_e(x):
    if not np.isnan(x['hh_f26a']):
        print(x['electricity'])
        new_prize = (x['electricity']/x['hh_f26a']) *unit_dict[x['hh_f26b']]
    else:
        new_prize = 0
    
    return pd.Series(new_prize,
                     index=['electricity'])

In [86]:
house_data['housing']=house_data.replace(np.nan,0).apply(convert_unit, axis=1)
house_data['electricity'] = house_data.apply(convert_unit_e, axis=1)
house_data['heat_electricity']=house_data['firewood']*52+house_data['electricity'].replace(np.nan,0)
house_data['telecommunication']=house_data['cell_phones']*12

house_data.loc[~house_data['electricity'].isna()]

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1100.0
0.0
0.0
0.0
3800.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
18671.0
1200.0
1200.0
2900.0
0.0
0.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
897.0
0.0
0.0
600.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

/home/insauer/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/home/insauer/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
590.0
0.0
0.0
0.0
0.0
800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1250.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1600.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1200.0
0.0
0.0
0.0
2600.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
980.0
800.0
0.0
2300.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4000.0
1600.0
800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1400.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
700.0
0.0
500.0
950.0
2000.0
0.0
1200.0
0.0
0.0
700.0
1000.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
666.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
0.0
0.0
0.0
0.0
0.0
876.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
2400.0
800.0
400.0
2000.0
1500.0
600.0
3200.0
700.0
800.0
1200.0
1300.0
2200.0
1380.0
850.0
2470.0
1050.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1300.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1650.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2000.0
2500.0
0.0
0.0
0.0
1900.0
1200.0
1200.0
1100.0
0.0
1600.0
1700.0
1200.0
2500.0
3000.0
99999.0
600.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1429.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
0.0
0.0
0.0
8000.0
0.0
0.0
900.0
0.0
0.0
0.0
0.0
1300.0
1700.0
2000.0
0.0
978.0
2000.0
5000.0
0.0
0.0
0.0
5000.0
1500.0
2500.0
6000.0
3000.0
0.0
800.0
3000.0
0.0
650.0
1200.0
20000.0
3000.0
99999.0
5000.0
3500.0
0.0
0.0
3000.0
0.0
0.0
0.0
500.0
1500.0
1800.0
2800.0
2000.0
0.0
0.0
0.0
1450.0
2760.0
1600.0
0.0
0.0
0.0
500.0
0.0
1255.0
0.0
1200.0
0.0
1800.0
800.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
4000.0
0.0
0.0
300.0
0.0
0.0
0.0
0.0
800.0
1460.0
600.0
0.0
0.0
0.0
0.0
650.0
650.0
0.0
1200.0
0.0
1200.0
400.0
3850.0
0.0
0.0
0.0
2100.0
0.0
0.0
2000.0
4500.0
3000.0
0.0
0.0
2000.0
2000.0
1000.0
1500.0
1000.0
1800.0
2000.0
3000.0
1500.0
300.0
0.0
2000.0
0.0
9999.0
0.0
2000.0
0.0
3000.0
1000.0
0.0
0.0
1200.0
0.0
1000.0
0.0
2000.0
1500.0
0.0
0.0
5000.0
3000.0
0.0
0.0
0.0
3500.0
0.0
0.0
0.0
3500.0
850.0
750.0
2800.0
0.0
2500.0
1235.0
1370.0
500.0
1500.0
99999.0
300.0
2000.0
1000.0
350.0
500.0
500.0
500.0
200.0
1500.0
500.0
0.0
2600.0
0.0
0.0
940.0
2000.0
0.0
0.0
700.0
0.0
0.0
1500.0
0.0
2500.0
1500.0
0.0
1600.0
1900.0
0.0
0.0
1500.0
0.0
0.0
0.0
1300.0
761.0
695.0
0.0
2135.0
4000.0
2600.0
2300.0
0.0
0.0
0.0
0.0
0.0
0.0
761.0
0.0
600.0
0.0
0.0
717.0
0.0
0.0
0.0
400.0
0.0
0.0
0.0
2500.0
600.0
0.0
1500.0
0.0
0.0
0.0
500.0
0.0
2600.0
1300.0
2600.0
4500.0
1500.0
2500.0
1700.0
4000.0
1200.0
0.0
2500.0
5300.0
2600.0
0.0
670.0
3000.0
2000.0
2500.0
600.0
99999.0
99999.0
0.0
3000.0
650.0
1500.0
0.0
500.0
0.0
2400.0
2500.0
600.0
650.0
500.0
800.0
0.0
0.0
0.0
0.0
2300.0
700.0
0.0
0.0
0.0
1700.0
1050.0
1000.0
300.0
1400.0
0.0
0.0
0.0
0.0
0.0
750.0
1100.0
0.0
0.0
0.0
0.0
1050.0
0.0
0.0
0.0
0.0
0.0
880.0
0.0
700.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1995.0
500.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5000.0
0.0
1500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
9999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0

0.0
0.0
0.0
0.0
0.0
1800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
1200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
900.0
0.0
6000.0
1200.0
1950.0
2200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1200.0
0.0
1500.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
30000.0
0.0
0.0
1250.0
1535.0
0.0
500.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3500.0
1000.0
500.0
1500.0
0.0
0.0
0.0
99999.0
0.0
700.0
0.0
2700.0
0.0
0.0
0.0
1300.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
2000.0
1000.0
600.0
0.0
0.0
0.0
0.0
0.0
3800.0
2000.0
1300.0
4000.0
1000.0
0.0
0.0
600.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
300.0
0.0
0.0
1600.0
2800.0
2000.0
0.0
1050.0
0.0
0.0
0.0
1200.0
0.0
0.0
0.0
13000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
5300.0
2300.0
1500.0
0.0
1200.0
0.0
3600.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3300.0
0.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0
0.0
0.0
0.0
1500.0
99999.0
0.0
0.0
0.0
0.0
6000.0
14416.0
3000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3000.0
3200.0
3100.0
2000.0
3000.0
2000.0
0.0
0.0
3000.0
200.0
250.0
0.0
2100.0
1500.0
450.0
3500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
999.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
1360.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
0.0
0.0
0.0
0.0
0.0
2000.0
2180.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
7000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
0.0
0.0
1200.0
1800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2400.0
0.0
3800.0

0.0
0.0
0.0
600.0
9000.0
350.0
1500.0
2000.0
3600.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0
600.0
0.0
0.0
0.0
1000.0
0.0
0.0
5000.0
1500.0
1500.0
0.0
0.0
0.0
1200.0
0.0
800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
794.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1300.0
1800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
400.0
0.0
0.0
950.0
0.0
1300.0
0.0
795.0
0.0
0.0
987.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
2500.0
0.0
0.0
5400.0
600.0
1500.0
0.0
5000.0
2500.0
0.0
1800.0
0.0
4500.0
0.0
99999.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
1000.0
2600.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
1500.0
0.0
2300.0
0.0
0.0
1200.0
4000.0
1000.0
0.0
2000.0
0.0
0.0
0.0
1500.0
1800.0
0.0
0.0
1500.0
0.0
0.0
1700.0
3000.0
3500.0
0.0
0.0
2500.0
1000.0
0.0
300.0
0.0
0.0
0.0
0.0
2000.0
3000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
1000.0
0.0
0.0
0.0
1500.0
0.0
3500.0
0.0
2300.0
500.0
536.0
1895.0
1500.0
2500.0
3500.0
750.0
2500.0
2000.0
2000.0
3200.0
3000.0
2000.0
0.0
0.0
0.0
1873.0
0.0
1000.0
1400.0
8000.0
600.0
0.0
1500.0
0.0
0.0
0.0
1800.0
0.0
3000.0
3500.0
2400.0
1900.0
0.0
0.0
0.0
0.0
0.0
2300.0
1500.0
1500.0
0.0
2400.0
9999.0
1500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
2500.0
1000.0
2500.0
0.0
0.0
0.0
1500.0
1000.0
2500.0
1000.0
99999.0
1000.0
2500.0
0.0
2000.0
1000.0
0.0
0.0
0.0
560.0
0.0
99999.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
675.0
0.0
0.0
0.0
0.0
0.0
6500.0
1000.0
500.0
500.0
1500.0
0.0
500.0
700.0
1500.0
1700.0
0.0
0.0
1200.0
1300.0
0.0
0.0
0.0
1000.0
0.0
99999.0
1693.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
900.0
0.0
3500.0
0.0
3000.0
0.0
1500.0
2250.0
0.0
0.0
1000.0
0.0
0.0
600.0
1500.0
0.0
5000.0
0.0
0.0
5500.0
15000.0
0.0
1500.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
3500.0
0.0
1800.0
1200.0
0.0
1500.0
0.0
0.0
4000.0
1700.0
0.0
2000.0
1000.0
1500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3000.0
0.0
9999.0
0.0
1800.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1800.0
99999.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
4500.0
4000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
99999.0
3000.0
8000.0
2500.0
9600.0
3000.0
2000.0
2000.0
12000.0
3000.0
0.0
5000.0
2000.0
5000.0
3000.0
0.0
0.0
0.0
0.0
2000.0
2500.0
0.0
0.0
2500.0
0.0
2000.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
7500.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
1500.0
0.0
0.0
1500.0
0.0
0.0
2500.0
0.0
0.0
3500.0
0.0
0.0
0.0
3000.0
0.0
1500.0
0.0
0.0
0.0
1865.0
1000.0
7000.0
0.0
1000.0
1000.0
600.0
0.0
1000.0
0.0
500.0
0.0
5000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2500.0
0.0
10700.0
0.0
1230.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
1000.0
0.0
0.0
1500.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1800.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
780.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2110.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1700.0
0.0
0.0
0.0
1300.0
2000.0
0.0
0.0
2500.0
1100.0
1200.0
3200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
99999.0
4500.0
200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4847.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
2000.0
900.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1400.0
0.0
1400.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
600.0
3000.0
0.0
0.0
1800.0
1430.0
1500.0
0.0
0.0
800.0
1500.0
0.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
2500.0
2000.0
0.0
300.0
4000.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
1990.0
0.0
0.0
0.0
0.0
1000.0
1000.0
1500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2300.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1300.0
1300.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2500.0
1700.0
0.0
800.0
950.0
3900.0
1500.0
0.0
0.0
500.0
0.0
0.0
450.0
1300.0
0.0
2600.0
0.0
0.0
1500.0
0.0
0.0
0.0
425.0
99999.0
0.0
0.0
0.0
1250.0
1450.0
0.0
1600.0
0.0
0.0
0.0
0.0
0.0
1400.0
1300.0
500.0
0.0
0.0
0.0
0.0
0.0
400.0
1200.0
0.0
500.0
950.0
0.0
0.0
0.0
1500.0
99999.0
500.0
0.0
0.0
0.0
1400.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2100.0
1400.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2400.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1200.0
0.0
775.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3000.0
3300.0
0.0
0.0
0.0
99999.0
800.0
0.0
4600.0
2500.0
1500.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2140.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
1300.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
300.0
0.0
0.0
4000.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
1180.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
1600.0
0.0
1000.0
0.0
1500.0
1500.0
0.0
0.0
0.0
0.0
0.0
1200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
640.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1100.0
2000.0
0.0
0.0
1500.0
0.0
0.0
0.0
1200.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0
0.0
2500.0
0.0
750.0
0.0
0.0
99999.0
0.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
15000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
800.0
700.0
1200.0
99999.0
99999.0
1100.0
1200.0
1700.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
950.0
0.0
500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2500.0
0.0
0.0
0.0
3540.0
2640.0
0.0
99999.0
0.0
0.0
1900.0
0.0
1200.0
0.0
0.0
99999.0
800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
900.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9000.0
2600.0
0.0
2000.0
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4500.0
2000.0
2500.0
0.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
5000.0
0.0
0.0
300.0
0.0
0.0
0.0
0.0
0.0
400.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5500.0
0.0
0.0
0.0
500.0
1000.0
4000.0
1500.0
0.0
0.0
1500.0
0.0
250.0
250.0
200.0
3500.0
99999.0
0.0
4000.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
1200.0
10644.0
2000.0
6000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4700.0
2500.0
0.0
1000.0
3500.0
0.0
99999.0
0.0
0.0
0.0
2500.0
8000.0
1200.0
0.0
99999.0
0.0
0.0
0.0
2000.0
0.0
4800.0
0.0
0.0
650.0
0.0
9999.0
4500.0
0.0
0.0
0.0
0.0
0.0
2500.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
1500.0
500.0
0.0
500.0
500.0
0.0
0.0
0.0
0.0
960.0
0.0
4500.0
4000.0
500.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4200.0
4260.0
2000.0
0.0
0.0
99999.0
8000.0
0.0
0.0
0.0
2100.0
5000.0
5000.0
2500.0
3650.0
0.0
0.0
879.0
500.0
0.0
0.0
1000.0
0.0
0.0
0.0
4000.0
0.0
0.0
500.0
99999.0
1300.0
0.0
0.0
3000.0
0.0
0.0
0.0
0.0
0.0
0.0
1200.0
0.0
99999.0
0.0
2500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
950.0
0.0
0.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1700.0
2000.0
1902.0
1500.0
0.0
0.0
0.0
0.0
0.0
300.0
1800.0
800.0
7500.0
0.0
500.0
2500.0
1700.0
4000.0
2500.0
1300.0
2100.0
2000.0
2500.0
1400.0
3000.0
1500.0
2800.0
3200.0
1500.0
4000.0
0.0
500.0
6000.0
2000.0
1500.0
2000.0

2000.0
2000.0
3200.0
1000.0
2500.0
1000.0
2200.0
3500.0
3000.0
5050.0
2000.0
1350.0
0.0
0.0
0.0
2000.0
0.0
0.0
0.0
0.0
1250.0
0.0
0.0
0.0
1950.0
2800.0
1350.0
1500.0
3500.0
0.0
0.0
0.0
1000.0
0.0
0.0
1650.0
6248.0
0.0
0.0
0.0
0.0
3500.0
0.0
0.0
4500.0
2200.0
2800.0
0.0
900.0
3000.0
0.0
1700.0
0.0
0.0
0.0
0.0
0.0
2600.0
0.0
0.0
99999.0
0.0
1500.0
0.0
0.0
0.0
2400.0
1650.0
0.0
0.0
0.0
1640.0
1500.0
1500.0
1500.0
500.0
2480.0
0.0
210.0
0.0
0.0
4100.0
2200.0
0.0
1260.0
2000.0
0.0
0.0
400.0
1500.0
0.0
1200.0
0.0
0.0
1500.0
2700.0
0.0
0.0
0.0
0.0
1000.0
0.0
99999.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6000.0
0.0
0.0
0.0
0.0
1800.0
700.0
1900.0
0.0
0.0
0.0
3600.0
0.0
0.0
0.0
0.0
800.0
0.0
0.0
0.0
1000.0
1200.0
0.0
0.0
0.0
0.0
0.0
0.0
1300.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
0.0
0.0
0.0
0.0
0.0
2300.0
0.0
0.0
0.0
500.0
0.0
0.0
2900.0
0.0
1900.0
0.0
500.0
500.0
500.0
0.0
0.0
0.0
2723.0
0.0
2000.0
600.0
0.0
0.0
0.0
0.0
1200.0
0.0
700.0
0.0
500.0
1500.0
1800.0
1500.0
1800.0
0.0
1900.0
4894.0
2200.0
2100.0
2000.0
0.0
0.0
0.0
2700.0
0.0
9999.0
0.0
2300.0
1400.0
4200.0
1700.0
500.0
600.0
480.0
950.0
2200.0
1300.0
0.0
2200.0
0.0
0.0
0.0
1000.0
1700.0
0.0
1500.0
0.0
99999.0
500.0
3800.0
0.0
0.0
3000.0
1500.0
1500.0
0.0
0.0
1200.0
480.0
0.0
0.0
99999.0
1500.0
800.0
1800.0
700.0
700.0
500.0
1000.0
0.0
99999.0
99999.0
2000.0
99999.0
0.0
0.0
0.0
1000.0
3800.0
5000.0
99999.0
99999.0
99999.0
3000.0
7000.0
4500.0
2000.0
2500.0
4500.0
4000.0
3000.0
1500.0
2300.0
2900.0
4500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1500.0
0.0
3000.0
250.0
0.0
0.0
0.0
1700.0
0.0
1200.0
1600.0
1100.0
440.0
0.0
1000.0
500.0
1500.0
1000.0
2000.0
9700.0
3500.0
5000.0
0.0
3000.0
4000.0
3600.0
0.0
1700.0
3500.0
0.0
4800.0
1000.0
700.0
0.0
2200.0
0.0
0.0
1000.0
0.0
0.0
3800.0
900.0
1400.0
1200.0
0.0
5000.0
3000.0
0.0
600.0
1800.0
1600.0
1200.0
0.0
0.0
300.0
0.0
2000.0
0.0
0.0
2000.0
0.0
0.0
0.0
1400.0
0.0
0.0
0.0
0.0
0.0
1700.0
0.0
0.0
0.0
0.0
0.0
0.0
2500.0
2600.0
0.0
8000.0
0.0
99999.0
0.0
0.0
0.0
3000.0
0.0
0.0
0.0
0.0
0.0
0.0
1200.0
500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0
1700.0
8000.0
0.0
2000.0
6000.0
99999.0
5000.0
500.0
3500.0
1200.0
25000.0
2500.0
5000.0
0.0
1800.0
18000.0
700.0
2000.0
2800.0
6270.0
2000.0
2500.0
7825.0
3620.0
1900.0
4000.0
4200.0
8000.0
1800.0
2500.0
2100.0
99999.0
18000.0
250.0
3100.0
99999.0
0.0
99999.0
800.0
0.0
1500.0
500.0
5000.0
0.0
0.0
99999.0
4500.0
0.0
430.0
0.0
0.0
6400.0
3200.0
0.0
4200.0
1000.0
2000.0
0.0
2000.0
5000.0
1000.0
3000.0
0.0
5500.0
3800.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
500.0
900.0
99999.0
0.0
0.0
976.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4500.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

,rent,hh_f04b,firewood,electricity,hh_f26a,hh_f26b,cell_phones,drinking_water,housing,heat_electricity,telecommunication
case_id,,,,,,,,,,,
101202860016,10000.0,5.0,350.0,13200.0,1.0,5.0,1200.0,1441.0,120000.0,31400.0,14400.0
101202860074,0.0,0.0,300.0,45600.0,1.0,5.0,16000.0,3000.0,0.0,61200.0,192000.0
101202860143,0.0,0.0,0.0,8400.0,1.0,5.0,5000.0,1854.0,0.0,8400.0,60000.0
101202880041,4000.0,5.0,500.0,224052.0,1.0,5.0,3000.0,2000.0,48000.0,250052.0,36000.0
101202880048,0.0,0.0,200.0,14400.0,1.0,5.0,2000.0,700.0,0.0,24800.0,24000.0
...,...,...,...,...,...,...,...,...,...,...,...
315526860326,0.0,0.0,0.0,45600.0,1.0,5.0,10000.0,4500.0,0.0,45600.0,120000.0
315532370211,1700.0,5.0,300.0,6000.0,1.0,5.0,1000.0,1500.0,20400.0,21600.0,12000.0
315532370231,0.0,0.0,0.0,10800.0,1.0,5.0,10000.0,800.0,0.0,10800.0,120000.0
315532370328,0.0,0.0,0.0,11712.0,1.0,5.0,5700.0,350.0,0.0,11712.0,68400.0
315546130115,0.0,0.0,0.0,54000.0,1.0,5.0,8680.0,0.0,0.0,54000.0,104160.0

In [87]:
consum['housing']=house_data['housing']
consum['heat_electricity']=house_data['heat_electricity']
consum['drinking_water']=house_data['drinking_water']
consum['telecommunication']=house_data['telecommunication']
consum

,education,health,housing,heat_electricity,drinking_water,telecommunication
case_id,,,,,,
101010160009,2000.0,3000.0,0.0,15600.0,50.0,0.0
101010160033,1100.0,2400.0,0.0,10400.0,0.0,0.0
101010160060,3400.0,0.0,0.0,26000.0,100.0,3600.0
101010160068,1650.0,1200.0,0.0,15600.0,100.0,0.0
101010160069,0.0,1200.0,0.0,2600.0,0.0,0.0
...,...,...,...,...,...,...
315556140342,0.0,1920.0,12000.0,24440.0,50.0,9600.0
315556140365,0.0,2600.0,0.0,9360.0,50.0,0.0
315556140388,0.0,0.0,12000.0,7800.0,100.0,6480.0
315556140411,0.0,2400.0,8400.0,20800.0,50.0,15600.0
315556140434,4100.0,0.0,0.0,20800.0,0.0,144000.0

# Food

In [89]:
food_data = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_g1.csv')
food_data = food_data[['case_id', 'hh_g05']]
food_data = food_data.replace(np.nan, 0)
food_data = food_data.groupby(['case_id']).sum()
#food_data = food_data.rename(columns={'hh_f04a': 'rent', 'hh_f18': 'firewood', 'hh_f25': 'electricity',
                                       # 'hh_f35': 'cell_phones', 'hh_f37': 'drinking_water'})
food_data

/home/insauer/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (5,8,11,15,18) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

              hh_g05
case_id
101010160009   510.0
101010160033   340.0
101010160060  1190.0
101010160068   600.0
101010160069   510.0
...              ...
315556140342  2250.0
315556140365  2490.0
315556140388  2315.0
315556140411  1790.0
315556140434  3165.0

[12271 rows x 1 columns]

In [90]:
food_data['food']=food_data['hh_g05']*52

In [91]:
food_data

              hh_g05      food
case_id
101010160009   510.0   26520.0
101010160033   340.0   17680.0
101010160060  1190.0   61880.0
101010160068   600.0   31200.0
101010160069   510.0   26520.0
...              ...       ...
315556140342  2250.0  117000.0
315556140365  2490.0  129480.0
315556140388  2315.0  120380.0
315556140411  1790.0   93080.0
315556140434  3165.0  164580.0

[12271 rows x 2 columns]

In [93]:
consum['food']=food_data['food']
consum

,education,health,housing,heat_electricity,drinking_water,telecommunication,food
case_id,,,,,,,
101010160009,2000.0,3000.0,0.0,15600.0,50.0,0.0,26520.0
101010160033,1100.0,2400.0,0.0,10400.0,0.0,0.0,17680.0
101010160060,3400.0,0.0,0.0,26000.0,100.0,3600.0,61880.0
101010160068,1650.0,1200.0,0.0,15600.0,100.0,0.0,31200.0
101010160069,0.0,1200.0,0.0,2600.0,0.0,0.0,26520.0
...,...,...,...,...,...,...,...
315556140342,0.0,1920.0,12000.0,24440.0,50.0,9600.0,117000.0
315556140365,0.0,2600.0,0.0,9360.0,50.0,0.0,129480.0
315556140388,0.0,0.0,12000.0,7800.0,100.0,6480.0,120380.0
315556140411,0.0,2400.0,8400.0,20800.0,50.0,15600.0,93080.0
315556140434,4100.0,0.0,0.0,20800.0,0.0,144000.0,164580.0

# Non-food expenditure

In [95]:
nf_exp = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_i1.csv')
nf_exp = nf_exp[['case_id', 'hh_i01', 'hh_i02', 'hh_i03']]
nf_exp = nf_exp.replace(np.nan, 0)
nf_exp

             case_id  hh_i01  hh_i02  hh_i03
0       101010160009     2.0     101     0.0
1       101010160009     2.0     102     0.0
2       101010160009     2.0     103     0.0
3       101010160009     2.0     104     0.0
4       101010160009     1.0     105    10.0
...              ...     ...     ...     ...
110434  315556140434     1.0     105    14.0
110435  315556140434     2.0     106     0.0
110436  315556140434     2.0     107     0.0
110437  315556140434     2.0     108     0.0
110438  315556140434     2.0     109     0.0

[110439 rows x 4 columns]

In [100]:
nf_exp_fuel = nf_exp.loc[nf_exp['hh_i02'].isin([101,102,103, 104,105])]
nf_exp_fuel = nf_exp_fuel.replace(np.nan, 0)
nf_exp_fuel = nf_exp_fuel.groupby(['case_id']).sum()
nf_exp_fuel['fuel']=nf_exp_fuel['hh_i03']*52
nf_exp_fuel

              hh_i01  hh_i02  hh_i03     fuel
case_id
101010160009     9.0     515    10.0    520.0
101010160033     9.0     515    10.0    520.0
101010160060     8.0     515    60.0   3120.0
101010160068     9.0     515    10.0    520.0
101010160069     9.0     515    10.0    520.0
...              ...     ...     ...      ...
315556140342     8.0     515    85.0   4420.0
315556140365     7.0     515   300.0  15600.0
315556140388     8.0     515    77.0   4004.0
315556140411     7.0     515   240.0  12480.0
315556140434     7.0     515   784.0  40768.0

[12271 rows x 4 columns]

In [102]:
nf_exp_np = nf_exp.loc[nf_exp['hh_i02'].isin([106])]
nf_exp_np = nf_exp_np.replace(np.nan, 0)
nf_exp_np = nf_exp_np.groupby(['case_id']).sum()
nf_exp_np['news_paper']=nf_exp_np['hh_i03']*52
nf_exp_np

              hh_i01  hh_i02  hh_i03  news_paper
case_id
101010160009     2.0     106     0.0         0.0
101010160033     2.0     106     0.0         0.0
101010160060     2.0     106     0.0         0.0
101010160068     2.0     106     0.0         0.0
101010160069     2.0     106     0.0         0.0
...              ...     ...     ...         ...
315556140342     2.0     106     0.0         0.0
315556140365     2.0     106     0.0         0.0
315556140388     2.0     106     0.0         0.0
315556140411     2.0     106     0.0         0.0
315556140434     2.0     106     0.0         0.0

[12271 rows x 4 columns]

In [115]:
nf_exp_pt = nf_exp.loc[nf_exp['hh_i02'].isin([107,108,109])]
nf_exp_pt = nf_exp_pt.replace(np.nan, 0)
nf_exp_pt = nf_exp_pt.groupby(['case_id']).sum()
nf_exp_pt['public_transport']=nf_exp_pt['hh_i03']*52
nf_exp_pt

              hh_i01  hh_i02  hh_i03  public_transport
case_id
101010160009     6.0     324     0.0               0.0
101010160033     6.0     324     0.0               0.0
101010160060     6.0     324     0.0               0.0
101010160068     6.0     324     0.0               0.0
101010160069     6.0     324     0.0               0.0
...              ...     ...     ...               ...
315556140342     5.0     324   160.0            8320.0
315556140365     6.0     324     0.0               0.0
315556140388     5.0     324   200.0           10400.0
315556140411     6.0     324     0.0               0.0
315556140434     6.0     324     0.0               0.0

[12271 rows x 4 columns]

In [105]:
nf_exp_2 = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_i2.csv')
nf_exp_2 = nf_exp_2[['case_id', 'hh_i04', 'hh_i05', 'hh_i06']]
nf_exp_2 = nf_exp_2.replace(np.nan, 0)
nf_exp_2

             case_id  hh_i04  hh_i05  hh_i06
0       101010160009     1.0     201   200.0
1       101010160009     1.0     202    50.0
2       101010160009     1.0     203   100.0
3       101010160009     2.0     204     0.0
4       101010160009     2.0     205     0.0
...              ...     ...     ...     ...
245415  315556140434     2.0     217     0.0
245416  315556140434     2.0     218     0.0
245417  315556140434     2.0     219     0.0
245418  315556140434     2.0     220     0.0
245419  315556140434     2.0     221     0.0

[245420 rows x 4 columns]

In [112]:
nf_exp_cosm = nf_exp_2.loc[nf_exp_2['hh_i05'].isin([201,202,203, 204, 205, 206, 207])]
nf_exp_cosm = nf_exp_cosm.replace(np.nan, 0)
nf_exp_cosm = nf_exp_cosm.groupby(['case_id']).sum()
nf_exp_cosm['hygiene']=nf_exp_cosm['hh_i06']*52
nf_exp_cosm

              hh_i04  hh_i05  hh_i06  hygiene
case_id
101010160009    10.0    1428   360.0  18720.0
101010160033    11.0    1428   580.0  30160.0
101010160060    11.0    1428   830.0  43160.0
101010160068     9.0    1428   820.0  42640.0
101010160069    11.0    1428   540.0  28080.0
...              ...     ...     ...      ...
315556140342    11.0    1428  1270.0  66040.0
315556140365    11.0    1428   580.0  30160.0
315556140388    11.0    1428   490.0  25480.0
315556140411    11.0    1428   640.0  33280.0
315556140434    11.0    1428   420.0  21840.0

[12271 rows x 4 columns]

In [113]:
nf_exp_tech = nf_exp_2.loc[nf_exp_2['hh_i05'].isin([209, 213, 214, 216, 217, 218, 220, 221])]
nf_exp_tech = nf_exp_tech.replace(np.nan, 0)
nf_exp_tech = nf_exp_tech.groupby(['case_id']).sum()
nf_exp_tech['technical_maintanance']=nf_exp_tech['hh_i06']*12
nf_exp_tech

              hh_i04  hh_i05  hh_i06  technical_maintanance
case_id
101010160009    15.0    1728    60.0                  720.0
101010160033    16.0    1728     0.0                    0.0
101010160060    16.0    1728     0.0                    0.0
101010160068    15.0    1728  1500.0                18000.0
101010160069    15.0    1728    80.0                  960.0
...              ...     ...     ...                    ...
315556140342    16.0    1728     0.0                    0.0
315556140365    16.0    1728     0.0                    0.0
315556140388    15.0    1728    90.0                 1080.0
315556140411    15.0    1728   120.0                 1440.0
315556140434    16.0    1728     0.0                    0.0

[12271 rows x 4 columns]

In [114]:
nf_exp_fuel_2 = nf_exp_2.loc[nf_exp_2['hh_i05'].isin([212])]
nf_exp_fuel_2 = nf_exp_fuel_2.replace(np.nan, 0)
nf_exp_fuel_2 = nf_exp_fuel_2.groupby(['case_id']).sum()
nf_exp_fuel_2['fuel_2']=nf_exp_fuel_2['hh_i06']*12
nf_exp_fuel_2

              hh_i04  hh_i05  hh_i06  fuel_2
case_id
101010160009     2.0     212     0.0     0.0
101010160033     2.0     212     0.0     0.0
101010160060     2.0     212     0.0     0.0
101010160068     2.0     212     0.0     0.0
101010160069     2.0     212     0.0     0.0
...              ...     ...     ...     ...
315556140342     2.0     212     0.0     0.0
315556140365     2.0     212     0.0     0.0
315556140388     2.0     212     0.0     0.0
315556140411     2.0     212     0.0     0.0
315556140434     2.0     212     0.0     0.0

[12271 rows x 4 columns]

In [116]:
nf_exp_don = nf_exp_2.loc[nf_exp_2['hh_i05'].isin([211])]
nf_exp_don = nf_exp_don.replace(np.nan, 0)
nf_exp_don = nf_exp_don.groupby(['case_id']).sum()
nf_exp_don['donation']=nf_exp_don['hh_i06']*12
nf_exp_don

              hh_i04  hh_i05  hh_i06  donation
case_id
101010160009     2.0     211     0.0       0.0
101010160033     2.0     211     0.0       0.0
101010160060     1.0     211   450.0    5400.0
101010160068     1.0     211   500.0    6000.0
101010160069     2.0     211     0.0       0.0
...              ...     ...     ...       ...
315556140342     1.0     211   150.0    1800.0
315556140365     2.0     211     0.0       0.0
315556140388     1.0     211   150.0    1800.0
315556140411     1.0     211   120.0    1440.0
315556140434     2.0     211     0.0       0.0

[12271 rows x 4 columns]

In [117]:
nf_exp_post = nf_exp_2.loc[nf_exp_2['hh_i05'].isin([210])]
nf_exp_post = nf_exp_post.replace(np.nan, 0)
nf_exp_post = nf_exp_post.groupby(['case_id']).sum()
nf_exp_post['postal_fees']=nf_exp_post['hh_i06']*12
nf_exp_post

              hh_i04  hh_i05  hh_i06  postal_fees
case_id
101010160009     2.0     210     0.0          0.0
101010160033     2.0     210     0.0          0.0
101010160060     2.0     210     0.0          0.0
101010160068     2.0     210     0.0          0.0
101010160069     2.0     210     0.0          0.0
...              ...     ...     ...          ...
315556140342     2.0     210     0.0          0.0
315556140365     2.0     210     0.0          0.0
315556140388     2.0     210     0.0          0.0
315556140411     2.0     210     0.0          0.0
315556140434     2.0     210     0.0          0.0

[12271 rows x 4 columns]

In [119]:
nf_exp_pets = nf_exp_2.loc[nf_exp_2['hh_i05'].isin([219])]
nf_exp_pets = nf_exp_pets.replace(np.nan, 0)
nf_exp_pets = nf_exp_pets.groupby(['case_id']).sum()
nf_exp_pets['pets']=nf_exp_pets['hh_i06']*12
nf_exp_pets

              hh_i04  hh_i05  hh_i06  pets
case_id
101010160009     2.0     219     0.0   0.0
101010160033     2.0     219     0.0   0.0
101010160060     2.0     219     0.0   0.0
101010160068     2.0     219     0.0   0.0
101010160069     2.0     219     0.0   0.0
...              ...     ...     ...   ...
315556140342     2.0     219     0.0   0.0
315556140365     2.0     219     0.0   0.0
315556140388     2.0     219     0.0   0.0
315556140411     2.0     219     0.0   0.0
315556140434     2.0     219     0.0   0.0

[12271 rows x 4 columns]

In [121]:
nf_exp_wages = nf_exp_2.loc[nf_exp_2['hh_i05'].isin([215])]
nf_exp_wages = nf_exp_wages.replace(np.nan, 0)
nf_exp_wages = nf_exp_wages.groupby(['case_id']).sum()
nf_exp_wages['wages']=nf_exp_wages['hh_i06']*12
nf_exp_wages

              hh_i04  hh_i05  hh_i06  wages
case_id
101010160009     2.0     215     0.0    0.0
101010160033     2.0     215     0.0    0.0
101010160060     2.0     215     0.0    0.0
101010160068     2.0     215     0.0    0.0
101010160069     2.0     215     0.0    0.0
...              ...     ...     ...    ...
315556140342     2.0     215     0.0    0.0
315556140365     2.0     215     0.0    0.0
315556140388     2.0     215     0.0    0.0
315556140411     2.0     215     0.0    0.0
315556140434     2.0     215     0.0    0.0

[12271 rows x 4 columns]

In [123]:
consum['sanitation']=nf_exp_cosm['hygiene']
consum['technical_maintanance']=nf_exp_tech['technical_maintanance']
consum['fuel_2']=nf_exp_fuel_2['fuel_2']
consum['charity']=nf_exp_don['donation']
consum['postal_fees']=nf_exp_post['postal_fees']
consum['pets']=nf_exp_pets['pets']
consum['wages']=nf_exp_wages['wages']
consum['fuel']=nf_exp_fuel['fuel']
consum['news_paper']=nf_exp_np['news_paper']
consum['fuel']=nf_exp_pt['public_transport']
consum

,education,health,housing,heat_electricity,drinking_water,telecommunication,food,sanitation,technical_maintanance,fuel_2,charity,postal_fees,pets,wages,fuel,news_paper
case_id,,,,,,,,,,,,,,,,
101010160009,2000.0,3000.0,0.0,15600.0,50.0,0.0,26520.0,18720.0,720.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160033,1100.0,2400.0,0.0,10400.0,0.0,0.0,17680.0,30160.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160060,3400.0,0.0,0.0,26000.0,100.0,3600.0,61880.0,43160.0,0.0,0.0,5400.0,0.0,0.0,0.0,0.0,0.0
101010160068,1650.0,1200.0,0.0,15600.0,100.0,0.0,31200.0,42640.0,18000.0,0.0,6000.0,0.0,0.0,0.0,0.0,0.0
101010160069,0.0,1200.0,0.0,2600.0,0.0,0.0,26520.0,28080.0,960.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315556140342,0.0,1920.0,12000.0,24440.0,50.0,9600.0,117000.0,66040.0,0.0,0.0,1800.0,0.0,0.0,0.0,8320.0,0.0
315556140365,0.0,2600.0,0.0,9360.0,50.0,0.0,129480.0,30160.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140388,0.0,0.0,12000.0,7800.0,100.0,6480.0,120380.0,25480.0,1080.0,0.0,1800.0,0.0,0.0,0.0,10400.0,0.0
315556140411,0.0,2400.0,8400.0,20800.0,50.0,15600.0,93080.0,33280.0,1440.0,0.0,1440.0,0.0,0.0,0.0,0.0,0.0
315556140434,4100.0,0.0,0.0,20800.0,0.0,144000.0,164580.0,21840.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [124]:
nf_exp_j = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_j.csv')
nf_exp_j = nf_exp_j[['case_id', 'hh_j01', 'hh_j02', 'hh_j03']]
nf_exp_j = nf_exp_j.replace(np.nan, 0)
nf_exp_j

             case_id  hh_j01  hh_j02  hh_j03
0       101010160009     2.0     301     0.0
1       101010160009     2.0     302     0.0
2       101010160009     2.0     303     0.0
3       101010160009     2.0     304     0.0
4       101010160009     2.0     305     0.0
...              ...     ...     ...     ...
478564  315556140434     2.0     335     0.0
478565  315556140434     2.0     336     0.0
478566  315556140434     2.0     337     0.0
478567  315556140434     2.0     338     0.0
478568  315556140434     2.0     339     0.0

[478569 rows x 4 columns]

In [126]:
clothes_list=list(np.arange(301,328))
nf_exp_clothes = nf_exp_j.loc[nf_exp_j['hh_j02'].isin(clothes_list)]
nf_exp_clothes = nf_exp_clothes.replace(np.nan, 0)
nf_exp_clothes = nf_exp_clothes.groupby(['case_id']).sum()
nf_exp_clothes['clothes']=nf_exp_clothes['hh_j03']*4
nf_exp_clothes

              hh_j01  hh_j02  hh_j03  clothes
case_id
101010160009    54.0    8478     0.0      0.0
101010160033    54.0    8478     0.0      0.0
101010160060    54.0    8478     0.0      0.0
101010160068    52.0    8478   750.0   3000.0
101010160069    54.0    8478     0.0      0.0
...              ...     ...     ...      ...
315556140342    51.0    8478  1400.0   5600.0
315556140365    52.0    8478  1400.0   5600.0
315556140388    52.0    8478  2200.0   8800.0
315556140411    49.0    8478  1700.0   6800.0
315556140434    52.0    8478  2700.0  10800.0

[12271 rows x 4 columns]

In [129]:
housing_list=list(np.arange(328,335)) + [338, 339]
nf_exp_house = nf_exp_j.loc[nf_exp_j['hh_j02'].isin(housing_list)]
nf_exp_house = nf_exp_house.replace(np.nan, 0)
nf_exp_house = nf_exp_house.groupby(['case_id']).sum()
nf_exp_house['housing']=nf_exp_house['hh_j03']*4
nf_exp_house

              hh_j01  hh_j02  hh_j03  housing
case_id
101010160009    18.0    2994     0.0      0.0
101010160033    18.0    2994     0.0      0.0
101010160060    18.0    2994     0.0      0.0
101010160068    18.0    2994     0.0      0.0
101010160069    17.0    2994   650.0   2600.0
...              ...     ...     ...      ...
315556140342    18.0    2994     0.0      0.0
315556140365    18.0    2994     0.0      0.0
315556140388    18.0    2994     0.0      0.0
315556140411    16.0    2994   430.0   1720.0
315556140434    18.0    2994     0.0      0.0

[12271 rows x 4 columns]

In [131]:
nf_exp_leisure = nf_exp_j.loc[nf_exp_j['hh_j02'].isin([335, 336])]
nf_exp_leisure = nf_exp_leisure.replace(np.nan, 0)
nf_exp_leisure = nf_exp_leisure.groupby(['case_id']).sum()
nf_exp_leisure['leisure']=nf_exp_leisure['hh_j03']*4
nf_exp_leisure

              hh_j01  hh_j02  hh_j03  leisure
case_id
101010160009     4.0     671     0.0      0.0
101010160033     4.0     671     0.0      0.0
101010160060     4.0     671     0.0      0.0
101010160068     4.0     671     0.0      0.0
101010160069     4.0     671     0.0      0.0
...              ...     ...     ...      ...
315556140342     4.0     671     0.0      0.0
315556140365     4.0     671     0.0      0.0
315556140388     4.0     671     0.0      0.0
315556140411     4.0     671     0.0      0.0
315556140434     4.0     671     0.0      0.0

[12271 rows x 4 columns]

In [132]:
nf_exp_k = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_k.csv')
nf_exp_k = nf_exp_k[['case_id', 'hh_k01', 'hh_k02', 'hh_k03']]
nf_exp_k = nf_exp_k.replace(np.nan, 0)
nf_exp_k

             case_id  hh_k01  hh_k02  hh_k03
0       101010160009     2.0     401     0.0
1       101010160009     2.0     402     0.0
2       101010160009     2.0     403     0.0
3       101010160009     2.0     404     0.0
4       101010160009     2.0     405     0.0
...              ...     ...     ...     ...
245415  315556140434     2.0     416     0.0
245416  315556140434     2.0     417     0.0
245417  315556140434     2.0     418     0.0
245418  315556140434     2.0     419     0.0
245419  315556140434     2.0     420     0.0

[245420 rows x 4 columns]

In [135]:
housing_list=list(np.arange(401,406)) + [411]
nf_exp_k_house = nf_exp_k.loc[nf_exp_k['hh_k02'].isin(housing_list)]
nf_exp_k_house = nf_exp_k_house.replace(np.nan, 0)
nf_exp_k_house = nf_exp_k_house.groupby(['case_id']).sum()
nf_exp_k_house['housing']=nf_exp_k_house['hh_k03']
nf_exp_k_house

              hh_k01  hh_k02  hh_k03  housing
case_id
101010160009    12.0    2426     0.0      0.0
101010160033    12.0    2426     0.0      0.0
101010160060    11.0    2426  2000.0   2000.0
101010160068    10.0    2426  2700.0   2700.0
101010160069    12.0    2426     0.0      0.0
...              ...     ...     ...      ...
315556140342    11.0    2426   460.0    460.0
315556140365    12.0    2426     0.0      0.0
315556140388    12.0    2426     0.0      0.0
315556140411    12.0    2426     0.0      0.0
315556140434    11.0    2426   300.0    300.0

[12271 rows x 4 columns]

In [136]:
tech_list=list(np.arange(408,412))+[419, 420]
nf_exp_k_tech = nf_exp_k.loc[nf_exp_k['hh_k02'].isin(tech_list)]
nf_exp_k_tech = nf_exp_k_tech.replace(np.nan, 0)
nf_exp_k_tech = nf_exp_k_tech.groupby(['case_id']).sum()
nf_exp_k_tech['technical_maintanance']=nf_exp_k_tech['hh_k03']
nf_exp_k_tech

              hh_k01  hh_k02  hh_k03  technical_maintanance
case_id
101010160009    12.0    2477     0.0                    0.0
101010160033    10.0    2477  1220.0                 1220.0
101010160060    11.0    2477  3500.0                 3500.0
101010160068    12.0    2477     0.0                    0.0
101010160069    10.0    2477  4800.0                 4800.0
...              ...     ...     ...                    ...
315556140342    12.0    2477     0.0                    0.0
315556140365    12.0    2477     0.0                    0.0
315556140388    12.0    2477     0.0                    0.0
315556140411    12.0    2477     0.0                    0.0
315556140434    12.0    2477     0.0                    0.0

[12271 rows x 4 columns]

In [137]:
nf_exp_k_leisure = nf_exp_k.loc[nf_exp_k['hh_k02'].isin([406, 407])]
nf_exp_k_leisure = nf_exp_k_leisure.replace(np.nan, 0)
nf_exp_k_leisure = nf_exp_k_leisure.groupby(['case_id']).sum()
nf_exp_k_leisure['leisure']=nf_exp_k_leisure['hh_k03']
nf_exp_k_leisure

              hh_k01  hh_k02  hh_k03  leisure
case_id
101010160009     4.0     813     0.0      0.0
101010160033     4.0     813     0.0      0.0
101010160060     4.0     813     0.0      0.0
101010160068     4.0     813     0.0      0.0
101010160069     4.0     813     0.0      0.0
...              ...     ...     ...      ...
315556140342     4.0     813     0.0      0.0
315556140365     4.0     813     0.0      0.0
315556140388     4.0     813     0.0      0.0
315556140411     4.0     813     0.0      0.0
315556140434     4.0     813     0.0      0.0

[12271 rows x 4 columns]

In [139]:
nf_exp_k_insurance = nf_exp_k.loc[nf_exp_k['hh_k02'].isin([412])]
nf_exp_k_insurance = nf_exp_k_insurance.replace(np.nan, 0)
nf_exp_k_insurance = nf_exp_k_insurance.groupby(['case_id']).sum()
nf_exp_k_insurance['insurance']=nf_exp_k_insurance['hh_k03']
nf_exp_k_insurance

              hh_k01  hh_k02  hh_k03  insurance
case_id
101010160009     2.0     412     0.0        0.0
101010160033     2.0     412     0.0        0.0
101010160060     2.0     412     0.0        0.0
101010160068     2.0     412     0.0        0.0
101010160069     2.0     412     0.0        0.0
...              ...     ...     ...        ...
315556140342     2.0     412     0.0        0.0
315556140365     2.0     412     0.0        0.0
315556140388     2.0     412     0.0        0.0
315556140411     2.0     412     0.0        0.0
315556140434     2.0     412     0.0        0.0

[12271 rows x 4 columns]

In [141]:
nf_exp_k_losses = nf_exp_k.loc[nf_exp_k['hh_k02'].isin([413])]
nf_exp_k_losses = nf_exp_k_losses.replace(np.nan, 0)
nf_exp_k_losses = nf_exp_k_losses.groupby(['case_id']).sum()
nf_exp_k_losses['losses']=nf_exp_k_losses['hh_k03']
nf_exp_k_losses

              hh_k01  hh_k02  hh_k03  losses
case_id
101010160009     2.0     413     0.0     0.0
101010160033     2.0     413     0.0     0.0
101010160060     1.0     413  1500.0  1500.0
101010160068     2.0     413     0.0     0.0
101010160069     2.0     413     0.0     0.0
...              ...     ...     ...     ...
315556140342     2.0     413     0.0     0.0
315556140365     2.0     413     0.0     0.0
315556140388     2.0     413     0.0     0.0
315556140411     2.0     413     0.0     0.0
315556140434     2.0     413     0.0     0.0

[12271 rows x 4 columns]

In [143]:
nf_exp_k_fees = nf_exp_k.loc[nf_exp_k['hh_k02'].isin([414])]
nf_exp_k_fees = nf_exp_k_fees.replace(np.nan, 0)
nf_exp_k_fees = nf_exp_k_fees.groupby(['case_id']).sum()
nf_exp_k_fees['legal_fees']=nf_exp_k_fees['hh_k03']
nf_exp_k_fees

              hh_k01  hh_k02  hh_k03  legal_fees
case_id
101010160009     2.0     414     0.0         0.0
101010160033     2.0     414     0.0         0.0
101010160060     2.0     414     0.0         0.0
101010160068     2.0     414     0.0         0.0
101010160069     2.0     414     0.0         0.0
...              ...     ...     ...         ...
315556140342     2.0     414     0.0         0.0
315556140365     2.0     414     0.0         0.0
315556140388     2.0     414     0.0         0.0
315556140411     2.0     414     0.0         0.0
315556140434     2.0     414     0.0         0.0

[12271 rows x 4 columns]

In [145]:
nf_exp_k_wedfun = nf_exp_k.loc[nf_exp_k['hh_k02'].isin([414, 415, 416, 417, 418])]
nf_exp_k_wedfun = nf_exp_k_wedfun.replace(np.nan, 0)
nf_exp_k_wedfun = nf_exp_k_wedfun.groupby(['case_id']).sum()
nf_exp_k_wedfun['wedding_funeral']=nf_exp_k_wedfun['hh_k03']
nf_exp_k_wedfun

              hh_k01  hh_k02   hh_k03  wedding_funeral
case_id
101010160009     7.0    2080  10300.0          10300.0
101010160033    10.0    2080      0.0              0.0
101010160060    10.0    2080      0.0              0.0
101010160068     9.0    2080    200.0            200.0
101010160069     9.0    2080    450.0            450.0
...              ...     ...      ...              ...
315556140342    10.0    2080      0.0              0.0
315556140365    10.0    2080      0.0              0.0
315556140388    10.0    2080      0.0              0.0
315556140411    10.0    2080      0.0              0.0
315556140434    10.0    2080      0.0              0.0

[12271 rows x 4 columns]

In [146]:
consum['clothing']=nf_exp_clothes['clothes']
consum['technical_maintanance']=nf_exp_tech['technical_maintanance']
consum['housing']= consum['housing'] + nf_exp_house['housing']
consum['leisure']=nf_exp_leisure['leisure']
consum['housing']= consum['housing'] + nf_exp_k_house['housing']
consum['technical_maintanance']= consum['technical_maintanance']+nf_exp_k_tech['technical_maintanance']
consum['leisure']= consum['leisure'] + nf_exp_k_leisure['leisure']
consum['insurance']=nf_exp_k_insurance['insurance']
consum['losses']=nf_exp_k_losses['losses']
consum['legal_fees']=nf_exp_k_fees['legal_fees']
consum['wedding_funeral']=nf_exp_k_wedfun['wedding_funeral']
consum

,education,health,housing,heat_electricity,drinking_water,telecommunication,food,sanitation,technical_maintanance,fuel_2,...,pets,wages,fuel,news_paper,clothing,leisure,insurance,losses,legal_fees,wedding_funeral
case_id,,,,,,,,,,,,,,,,,,,,,
101010160009,2000.0,3000.0,0.0,15600.0,50.0,0.0,26520.0,18720.0,720.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10300.0
101010160033,1100.0,2400.0,0.0,10400.0,0.0,0.0,17680.0,30160.0,1220.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160060,3400.0,0.0,2000.0,26000.0,100.0,3600.0,61880.0,43160.0,3500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1500.0,0.0,0.0
101010160068,1650.0,1200.0,2700.0,15600.0,100.0,0.0,31200.0,42640.0,18000.0,0.0,...,0.0,0.0,0.0,0.0,3000.0,0.0,0.0,0.0,0.0,200.0
101010160069,0.0,1200.0,2600.0,2600.0,0.0,0.0,26520.0,28080.0,5760.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315556140342,0.0,1920.0,12460.0,24440.0,50.0,9600.0,117000.0,66040.0,0.0,0.0,...,0.0,0.0,8320.0,0.0,5600.0,0.0,0.0,0.0,0.0,0.0
315556140365,0.0,2600.0,0.0,9360.0,50.0,0.0,129480.0,30160.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5600.0,0.0,0.0,0.0,0.0,0.0
315556140388,0.0,0.0,12000.0,7800.0,100.0,6480.0,120380.0,25480.0,1080.0,0.0,...,0.0,0.0,10400.0,0.0,8800.0,0.0,0.0,0.0,0.0,0.0
315556140411,0.0,2400.0,10120.0,20800.0,50.0,15600.0,93080.0,33280.0,1440.0,0.0,...,0.0,0.0,0.0,0.0,6800.0,0.0,0.0,0.0,0.0,0.0
315556140434,4100.0,0.0,300.0,20800.0,0.0,144000.0,164580.0,21840.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10800.0,0.0,0.0,0.0,0.0,0.0

# Gifts

In [150]:
nf_exp_q = pd.read_csv('/home/insauer/projects/WB_model/Data_Malawi/MWI_2010_IHS-III_v01_M_CSV/Full_Sample/Household/hh_mod_q.csv')
nf_exp_gifts = nf_exp_q[['case_id', 'hh_q02a', 'hh_q02b', 'hh_q02c']]
nf_exp_gifts = nf_exp_gifts.replace(np.nan, 0)
nf_exp_gifts = nf_exp_gifts.groupby(['case_id']).sum()
nf_exp_gifts['gifts']=nf_exp_gifts.sum(axis=1)
nf_exp_gifts

              hh_q02a  hh_q02b  hh_q02c    gifts
case_id
101010160009   1100.0      0.0      0.0   1100.0
101010160033      0.0      0.0      0.0      0.0
101010160060    300.0      0.0      0.0    300.0
101010160068   1800.0      0.0      0.0   1800.0
101010160069    800.0      0.0   3000.0   3800.0
...               ...      ...      ...      ...
315556140342      0.0   3000.0      0.0   3000.0
315556140365    800.0      0.0      0.0    800.0
315556140388   5000.0      0.0      0.0   5000.0
315556140411      0.0      0.0      0.0      0.0
315556140434      0.0      0.0  10000.0  10000.0

[12271 rows x 4 columns]

In [151]:
consum['gifts']=nf_exp_gifts['gifts']
consum

,education,health,housing,heat_electricity,drinking_water,telecommunication,food,sanitation,technical_maintanance,fuel_2,...,wages,fuel,news_paper,clothing,leisure,insurance,losses,legal_fees,wedding_funeral,gifts
case_id,,,,,,,,,,,,,,,,,,,,,
101010160009,2000.0,3000.0,0.0,15600.0,50.0,0.0,26520.0,18720.0,720.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10300.0,1100.0
101010160033,1100.0,2400.0,0.0,10400.0,0.0,0.0,17680.0,30160.0,1220.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101010160060,3400.0,0.0,2000.0,26000.0,100.0,3600.0,61880.0,43160.0,3500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1500.0,0.0,0.0,300.0
101010160068,1650.0,1200.0,2700.0,15600.0,100.0,0.0,31200.0,42640.0,18000.0,0.0,...,0.0,0.0,0.0,3000.0,0.0,0.0,0.0,0.0,200.0,1800.0
101010160069,0.0,1200.0,2600.0,2600.0,0.0,0.0,26520.0,28080.0,5760.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,450.0,3800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315556140342,0.0,1920.0,12460.0,24440.0,50.0,9600.0,117000.0,66040.0,0.0,0.0,...,0.0,8320.0,0.0,5600.0,0.0,0.0,0.0,0.0,0.0,3000.0
315556140365,0.0,2600.0,0.0,9360.0,50.0,0.0,129480.0,30160.0,0.0,0.0,...,0.0,0.0,0.0,5600.0,0.0,0.0,0.0,0.0,0.0,800.0
315556140388,0.0,0.0,12000.0,7800.0,100.0,6480.0,120380.0,25480.0,1080.0,0.0,...,0.0,10400.0,0.0,8800.0,0.0,0.0,0.0,0.0,0.0,5000.0
315556140411,0.0,2400.0,10120.0,20800.0,50.0,15600.0,93080.0,33280.0,1440.0,0.0,...,0.0,0.0,0.0,6800.0,0.0,0.0,0.0,0.0,0.0,0.0
315556140434,4100.0,0.0,300.0,20800.0,0.0,144000.0,164580.0,21840.0,0.0,0.0,...,0.0,0.0,0.0,10800.0,0.0,0.0,0.0,0.0,0.0,10000.0

In [152]:
consum['total_expenditure']=consum.sum(axis=1)
consum

,education,health,housing,heat_electricity,drinking_water,telecommunication,food,sanitation,technical_maintanance,fuel_2,...,fuel,news_paper,clothing,leisure,insurance,losses,legal_fees,wedding_funeral,gifts,total_expenditure
case_id,,,,,,,,,,,,,,,,,,,,,
101010160009,2000.0,3000.0,0.0,15600.0,50.0,0.0,26520.0,18720.0,720.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10300.0,1100.0,78010.0
101010160033,1100.0,2400.0,0.0,10400.0,0.0,0.0,17680.0,30160.0,1220.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62960.0
101010160060,3400.0,0.0,2000.0,26000.0,100.0,3600.0,61880.0,43160.0,3500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1500.0,0.0,0.0,300.0,150840.0
101010160068,1650.0,1200.0,2700.0,15600.0,100.0,0.0,31200.0,42640.0,18000.0,0.0,...,0.0,0.0,3000.0,0.0,0.0,0.0,0.0,200.0,1800.0,124090.0
101010160069,0.0,1200.0,2600.0,2600.0,0.0,0.0,26520.0,28080.0,5760.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,450.0,3800.0,71010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315556140342,0.0,1920.0,12460.0,24440.0,50.0,9600.0,117000.0,66040.0,0.0,0.0,...,8320.0,0.0,5600.0,0.0,0.0,0.0,0.0,0.0,3000.0,250230.0
315556140365,0.0,2600.0,0.0,9360.0,50.0,0.0,129480.0,30160.0,0.0,0.0,...,0.0,0.0,5600.0,0.0,0.0,0.0,0.0,0.0,800.0,178050.0
315556140388,0.0,0.0,12000.0,7800.0,100.0,6480.0,120380.0,25480.0,1080.0,0.0,...,10400.0,0.0,8800.0,0.0,0.0,0.0,0.0,0.0,5000.0,199320.0
315556140411,0.0,2400.0,10120.0,20800.0,50.0,15600.0,93080.0,33280.0,1440.0,0.0,...,0.0,0.0,6800.0,0.0,0.0,0.0,0.0,0.0,0.0,185010.0
315556140434,4100.0,0.0,300.0,20800.0,0.0,144000.0,164580.0,21840.0,0.0,0.0,...,0.0,0.0,10800.0,0.0,0.0,0.0,0.0,0.0,10000.0,376420.0

In [154]:
consum.sort_values(by='total_expenditure')

,education,health,housing,heat_electricity,drinking_water,telecommunication,food,sanitation,technical_maintanance,fuel_2,...,fuel,news_paper,clothing,leisure,insurance,losses,legal_fees,wedding_funeral,gifts,total_expenditure
case_id,,,,,,,,,,,,,,,,,,,,,
311044960058,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
205022400027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1820.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2320.0
310031000138,0.0,660.0,0.0,1560.0,0.0,0.0,0.0,0.0,400.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2620.0
313065000126,0.0,0.0,0.0,0.0,50.0,0.0,2600.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2650.0
311061820145,0.0,240.0,0.0,2600.0,0.0,0.0,1040.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3880.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311200970272,1800.0,3880.0,24250.0,15600.0,600.0,18000.0,156520.0,65520.0,10935720.0,0.0,...,0.0,0.0,15200.0,0.0,0.0,0.0,0.0,0.0,0.0,11237090.0
302032560182,8200.0,0.0,0.0,0.0,0.0,11999988.0,87360.0,4680.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2800.0,12103028.0
107347620169,117750.0,0.0,132850.0,46200.0,2240.0,240000.0,1033240.0,330200.0,2406000.0,3600000.0,...,0.0,31200.0,118000.0,0.0,164000.0,0.0,0.0,40000.0,250000.0,12171680.0
315382780002,1086100.0,0.0,154800.0,60000.0,8000.0,238800.0,1559740.0,344240.0,7291920.0,330000.0,...,150800.0,83200.0,242400.0,32000.0,90000.0,0.0,0.0,22000.0,177000.0,12339000.0
210777250165,10401999.0,0.0,1070000.0,60000.0,3000.0,600000.0,1721980.0,1092000.0,2402400.0,300000.0,...,0.0,364000.0,0.0,0.0,25000.0,0.0,0.0,0.0,120000.0,18250379.0

In [153]:
consum.to_csv('/home/insauer/projects/WB_model/Data_Malawi/expenditure.csv')